[workspace]
authors = ["davidfekke <david@fekke.com>"]
channels = ["conda-forge"]
name = "individual-capstone-davidfekke"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
ipykernel = ">=7.1.0,<8"
jupyter = ">=1.1.1,<2"
pandas = ">=3.0.0,<4"
numpy = ">=2.4.1,<3"
matplotlib = ">=3.10.8,<4"
scikit-learn = "1.5.1.*"
seaborn = ">=0.13.2,<0.14"
